#!/bin/sh

[ "$(uci -q get ikev2-site-link.main.enabled)" = 1 ] || exit 0
[ "$(uci -q get ikev2-site-link.main.role)" = source ] || exit 0

case "${ACTION:-}" in
	ifup | ifupdate)
		[ "${INTERFACE:-}" = wan ] || exit 0
		/usr/libexec/ikev2-site-link connect >/dev/null 2>&1 &
		;;
esac

