#!/bin/sh /etc/rc.common

USE_PROCD=1
START=98
STOP=78

start_service() {
	[ "$(uci -q get ikev2-site-link.main.enabled)" = 1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/libexec/ikev2-site-link monitor
	procd_set_param respawn 5 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger ikev2-site-link
}
